version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo "Zipping application..."
      - zip -r app.zip ./Build-cp/*
      - echo "Uploading to S3..."


artifacts:
  files:
    - app.zip
  discard-paths: yes
